### ISSUE TITLE
Duplicated token in parser error

### ISSUE THREAD

**Issue by stefanofornari** [beanshell/beanshell#517] opened 2018-09-12 05:58 UTC
java -cp bsh-2.1.0-SNAPSHOT.jar bsh.Interpreter
BeanShell 2.1.0-SNAPSHOT - by Pat Niemeyer (pat@pat.net)
bsh % class {
// Error: Parser Error: In file: <unknown> Encountered:  **"{" "{"**  at line 1, column 7.

**Comment by nickl-** [comment] 2018-09-14 19:28
@stefanofornari is there a question here?

Please elaborate...

**Comment by stefanofornari** [comment] 2018-09-14 22:18
it is a bug report ("{" "{") seems redundant to me...

**Comment by nickl-** [comment] 2018-09-17 06:39
It is a parser error and not a bug report... there is a missing `AmbiguousName` expected after class and before the `{`. The grammar does not support `class {` and the parser tells us that it encountered `{` which it didn't understand.

Seems to be the correct response to me.

**Comment by stefanofornari** [comment] 2018-09-17 07:32
Is the fact that `{` is repeated twice a bug? 

// Error: Parser Error: In file: Encountered: `"{" "{"` at line 1, column 7.

**Comment by nickl-** [comment] 2018-09-20 14:15
I wouldn't exactly call it a bug but lets keep thin open and look into where this duplication comes from and how we can make it go away.

**Comment by nickl-** [comment] 2019-06-15 12:06
Fixed in 5c0e5d6 

**Closed: Fixed**

**Closed by nickl-** 2019-06-15 12:06 UTC
