### ISSUE TITLE
try/finally does not work when EvalError thrown

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#546] opened 2019-03-28 22:10 UTC
BeanShell will not run the finally block when anything other than a TargetError is thown.  So if some other error flavour happens such as an EvalError the finally block is not executed.  Here is a simple and common enough test case to cause an EvalError with in a try block:

```java
   helper(int a) {
      return this;
   }

   try {
      helper(1,2,3);
   } finally {
      print("an error occurred");
   }
```

I had a look at [BSHTryStatement](https://github.com/beanshell/beanshell/blob/fdddee3de948c9e6babb2d1337028f6fd0a2ba5c/src/main/java/bsh/BSHTryStatement.java#L85) and the problem seems obvious enough:

```java
        try {
            ret = tryBlock.eval(callstack, interpreter);
        }
        catch( TargetError e ) {
            thrown = e.getTarget();
            // clean up call stack grown due to exception interruption
            while ( callstack.depth() > callstackDepth )
                callstack.pop();
        } finally {
            // unwrap the target error
            while ( null != thrown && thrown.getCause() instanceof TargetError )
                thrown = ((TargetError) thrown.getCause()).getTarget();

            // try block finished auto close try-with-resources
            if (null != this.tryWithResources) {
                List<Throwable> tlist = this.tryWithResources.autoClose();
                for (Throwable t: tlist) // Java 9/10 treats this differently from 8
                    if (null != thrown && thrown != t)
                        thrown.addSuppressed(t);
            }
        }
```
TargetErrors are captured, but everything else is not.  The mechanism to run the final block is only invoked with TargetErrors.  

Is there a reason that other errors were excluded, or do you think that this is just an oversight?  It looks easy enough to fix, but I maybe missing something.

**Comment by nickl-** [comment] 2019-03-29 22:32
TargetError is specifically used as a roll up container for the actual `Exceptions` thrown which it will report on. As is evident from the `getCause` and `getTarget` iterations, if an exception is thrown in `try`, `TargetError` is your guy.

Now you are not referring to `Exceptions` though but specifically an `EvalError`. I'll have to go check again but I have a suspicion that we abort on those. Something went wrong and from that state there is not much to do to recover from or too, is the understanding. Think blue screen...

Unless you think it should not be an evaluation error in this specific instance (nothing to do with it being inside a try block though but instead its cause is suspect) and there is a way to recover perhaps (not by processing the finally block... script is broke) then we should handle it differently and not have an `EvalError`.

I could be wrong...

**Comment by opeongo** [comment] 2019-03-30 03:06
My real case is almost exactly as shown in the example:  a scripted method was called with the wrong number of args, and it was inside a try block.  And it threw an EvalError, and I think that EvalError is an appropriate Throwable for this situation.

So the core of this problem is similar to the undeclared variable issue described by @drosenbauer:  EvalErrors cannot be caught.

```java
try {
  throw new EvalError("boom");
} catch (EvarError ee) {
  System.err.println("never ever gets here");
} finally {
  System.err.println("never gets here either");
}
```
I think that you are right to be thinking blue screen, possibly unreliable interpreter state.  Maybe it isn't safe to continue.  But even to skip going in to the catch block?  Even to skip the finally block?

I am using BeanShell embedded in a system to run control scripts.  In this context it is important to be able to catch errors and try to unwind resources.  Having large classes of errors/exceptions that cannot be caught is a bit of a shortcoming.

It looks like it would be easy to change BSHTryStatement so that it allows catching all Throwables.  But as you suggest I am not sure of reliability/safety of doing so.  I would have to think about and analyze what could go wrong, but even then I doubt to be aware of all the issues.  The best I can to is make a change and put together a suite of tests, and see what happens.

**Comment by nickl-** [comment] 2019-03-31 12:08
`EvalError` should be reserved for unrecoverable problems and should abort the script. The purpose go the `TargetError` is specifically to be able to roll up exceptions as it is implemented and will not work correctly if we change it, iow we will not be able to catch NPE or anything specific.

The solution is to change whatever might be recoverable to throw an exception instead of `EvalError` which is something that can be caught and recovered from not to attempt to catch `EvalError` which purpose is specifically to abort script. Make senes?...

**Comment by opeongo** [comment] 2019-04-02 18:43
Agreed.

I think that you are right that any changes will have to be made carefully on a case-by-case basis.  Ideally the long term goal would be to convert all recoverable Interpreter errors to TargetErrors.

What type of errors do you see as being so unrecoverable that they cannot be caught at the scripting level?

**Comment by nickl-** [comment] 2019-05-02 15:47
@opeongo with JAVA we have compile time errors and runtime errors with beanshell we do not compile.  I would assume that everything that cannot compile in JAVA are considered not recoverable or `EvalError` type.

**Comment by opeongo** [comment] 2019-05-28 16:10
Also see the relevant comments about try/catch from @patn in issue #151.

**Comment by nickl-** [comment] 2019-05-28 17:06
@opeongo So can we close this as "works as  implemented" and that we will not be catching `EvalError` in try catch.

**Comment by drosenbauer** [comment] 2019-05-28 18:24
>  I would assume that everything that cannot compile in JAVA are considered not recoverable or EvalError type.

I don't necessarily agree with this.

For an example, consider a script modified from the initial example:

```
   helper(int a) {
      return this;
   }

   try {
      connection = openDatabaseConnection();
      doStuff(connection);
      helper(1,2,3);
      finishStuff(connection);
   } finally {
      cleanUpStuff();
   }
```

In Java, of course, the entire class would fail to compile because `helper(int, int, int)` does not resolve and is thus a compile-time semantic error. If the call to `helper` were dynamically invoked via Java reflection, the call to `helper(1, 2, 3)` would throw a catchable `IllegalArgumentException`.

In Beanshell, the script parses grammatically, but semantics are evaluated as each statement is executed. The connection would be opened, then the stuff would be done, and then a "compiler type" semantic error would be encountered. As it stands, this would throw an EvalError and abort the script. There would be no opportunity to clean up the "stuff", leaving the operation halfway completed and a dangling database connection.

The problem is pernicious enough that I tend to write my application's Beanshell scripts in a Java IDE to catch semantic errors and then copy-paste them into Beanshell. The fact that the application I work with has an `#include` type concept makes things worse.

**Comment by nickl-** [comment] 2019-05-29 13:20
@drosenbauer 
>  If the call to helper were dynamically invoked via Java reflection, the call to helper(1, 2, 3) would throw a catchable IllegalArgumentException.


Your script would always throw the `IllegalArgumentException` so is there any advantage? Will this help you find the problem or cause more obfuscation?

The question is whether this is a syntactical error (compile time error in JAVA) or a valid execution error.

We could also treat this in a similar manner as for ex. JavaScript does and simply ignore the additional arguments. Again this obfuscates the problem which makes debugging more difficult.

Can you motivate why this should not be considered a syntax error?

**Comment by drosenbauer** [comment] 2019-05-29 13:30
The advantage is that I can handle the error by cleaning up the partially-finished operation. I agree that the script will always fail. But if the script runs within the application 30 times before I notice that it's failing, I won't have 30 partially finished operations that I now have to clean up by hand.

**Comment by drosenbauer** [comment] 2019-05-29 13:35
In other words, I agree that it's a syntax error, but that's a separate question from whether it ought to be an uncatchable abort. In Java terms, it's probably an `Error` and not an `Exception`. 

It's something that you _should not_ catch, in terms of best practice, but in specific circumstances, you may want to do something before aborting. You aren't supposed to catch Throwable, but you can.

**Comment by nickl-** [comment] 2019-05-29 16:24
@drosenbauer but now the script cannot run 30 times as it will be aborted.

In JAVA `IllegalArgumentException` is a runtime exception because we programatically (at runtime) assign the arguments, it may or may not be correct. This is not the case with your example, it will never be correct and is not a runtime exception.

IMO The best way to deal with this error is to abort the script. Unless you can adequately motivate the contrary, I am still not convinced.

**Comment by drosenbauer** [comment] 2019-05-31 14:11
You’re still thinking of the scripts as standalone executions rather than
hooks embedded in a larger application. In my case, the scripts are invoked
by the larger application as business logic to handle events in the system.
30 events mean 30 independent Beanshell script executions. (Possibly more
if the application interprets the error as something retryable.)

In my mind, this embedded case is the primary use case for Beanshell and so
should be accounted for at least as an option.

**Comment by nickl-** [comment] 2019-05-31 15:15
Surely your hook/plugin/embedded system is aware of failing scripts and they can be rectified. What you are proposing instead is for failing scripts to succeed, how does this allow us to find problems.

The question is not about the use case the question is whether syntax errors should be catchable.

**Comment by nickl-** [comment] 2019-05-31 15:22
> The question is not about the use case the question is whether syntax errors should be catchable.

Or more specifically, as this conversation is leaning towards, whether incorrect arguments should be considered a syntax error or a catchable runtime error. Unless you also want to catch incorrect function names or general parser errors as well?

**Comment by drosenbauer** [comment] 2019-06-04 20:24
I think that general parser errors - i.e. the code provided doesn't match the grammar - are a valid abort scenario. If the provided text cannot be parsed into an AST, there's absolutely no way to run it, and no part of the code can be executed. In fact, there's nothing _to_ run, since no code tree was produced. So the string `&ab%12` would throw an exception at parse time.

What I'm getting at here is essentially whether Beanshell should act more like a static language (where all names must be known at parse time) or more like a dynamic language (where they are not). In dynamic languages like Python, after things have been parsed, errors like "bad function name" _are_ catchable (as _NameErrors_, in that case). They're treated as runtime interpreter errors, not syntax errors.

In its dynamic and shell modes, Groovy also provides a similar exception (_MissingMethodException_). This is particularly notable in Groovy's case because it is truly compiling to Java bytecode but goes out of its way to make this catchable at runtime.

```
groovy:000> def a() { return "hi" }
===> true

groovy:000> a()
===> hi

groovy:000> a(1)
ERROR groovy.lang.MissingMethodException:
No signature of method: groovysh_evaluate.a() is applicable for argument types: (java.lang.Integer) values: [1]

groovy:000> try { a(1); } catch(MissingMethodException e) { println "error" }
error
```

Perl even provides a keyword (eval) that is capable of catching aborts, which can sometimes be initiated by a poorly coded library that one has no control over.

My opinion (and I know we disagree) is that since Beanshell is, at its core, a scripting language, it should behave like one.

**Comment by nickl-** [comment] 2019-06-08 05:38
The issue you are failing to raise is much bigger than function arguments or missing variables and we keep going around in circles because you refuse to interrogate superficial problems or even scratch the surface and insist on idealistic solutions backed by nonsensical look-but-they-do-it defences. 

You cannot approach a problem with a solution in hand, first identify the problem then apply the appropriate solution. Forget about chasing solutions and trying to force the conditions in order to realise an ideal outcome, it will end in disaster. Look for the problem not for the solution, if you have trouble applying a fix then you are looking at symptoms and haven't found the problem yet. Once you realise the problem completely the solution will be an obvious choice of options, one of many. It doesn't matter what the solution is the only important thing is to resolve the issue, then there will be no more problem.

If you are keen to find a solution, which it appears you are, then I suggest start by listing all the `EvalError` causes and record as much relevant information as possible like location thrown, condition, etc. especially information for grouping. The more similarities different causes have the more likely we can treat them the same. Once we have a comprehensive overview of the affected area we will gain a better understanding of the impact. Identifying distinctions which will assist with their separation and type association.

I have created a new issue #556 for defining the problem properly which includes a link to a google docs sheet which we can use. Email me a gmail account and I will grant you access.

You have confirmed that `EvalError` works correctly. 

> I think that general parser errors - i.e. the code provided doesn't match the grammar - are a valid abort scenario.

Since parser errors are of type `EvalError` then you agree that try/finally works as implemented script aborted.

**Closed: works as implemented**

**Closed by nickl-** 2019-06-08 05:38 UTC
Labels: enhancement, feature

**Comment by nickl-** [comment] 2019-06-15 11:12
`InvocationTargetException` already result in `TargetError`

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/BshMethod.java#L266-L270

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/BSHMethodInvocation.java#L77-L94
