### ISSUE TITLE
Interpreter in Processing IDE

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#487] opened 2017-09-29 00:37 UTC
Trying to get beanshell working in processing 3.0a5 IDE. Not sure why the processing method calls don't work. Any tips would be much appreciated!

Reported by: rtavakko

Original Ticket: [beanshell/support-requests/7](https://sourceforge.net/p/beanshell/support-requests/7)

**Comment by opeongo** [comment] 2019-11-28 19:29
There is not enough information here about what the problem is.  I suggest to close this with 'insufficient information to reproduce'

**Comment by nickl-** [comment] 2020-01-18 15:57
Tx @opeongo 

**Close: insufficient information to reproduce**

**Closed by nickl-** 2020-01-18 15:57 UTC
Labels: Interpreter, auto-migrated sourceforge, support
