### ISSUE TITLE
BigDecimal problem

### ISSUE THREAD

**Issue by sergioszy** [beanshell/beanshell#609] opened 2021-09-24 20:12 UTC
Hi,
We have been handling this problem. But I think that it is convenient to correct it.
This statement gives an error:
varDec = new BigDecimal( 123.456789 ).setScale( 2, RoundingMode.HALF_UP );
// Error: Evaluation Error: Error in method invocation: Method setScale(int, RoundingMode) not found in class'bsh.Primitive'

It is annoying when it occurs in class attributes or variables that have to be BigDecimal, as in use cases in jdbc and jpa.
It forces us to duplicate the variables and have a special treatment for those that are BigDecimal or BigInteger.
I think it has to do with the improvement of treating BigDecimal and BigInteger as primitives.

Thanks in advance
Best regards

**Comment by nickl-** [comment] 2021-11-12 11:38
> Hi, we made some modifications to Primitive.java and Types.java, that served us a lot.

Looks like you just removed the upscaling/downscaling features, unless I am reading the patch direction incorrectly.

Since we have decided to include the Bigs as primitives it is reasonable to then accept we should also port the interfaces to primitives. I think the more appropriate fix would be to implement the upscaled methods (even if just upscaling and calling them on BigDecimal for example) when detecting the method calls, instead of failing with a method not found.

**Comment by sergioszy** [comment] 2021-11-12 12:20
Hi,
If I use beanshell as I download it, this statement does not work, it gives the indicated error.
```
varDec = new BigDecimal( 123.456789 ).setScale( 2, RoundingMode.HALF_UP );
// Error: Evaluation Error: Error in method invocation: Method setScale(int, RoundingMode) not found in class'bsh.Primitive'

``` 
Is there any other way or configuration, so that not produce that error; and that it is not necessary to introduce the modifications that I made to Primitive and Types?

Thank you very much.

**Comment by nickl-** [comment] 2021-11-15 08:04
There is no quick fix no.

We need to implement the method `setScale`...all the `BigDecimal` methods actually... on `bsh.Primitive`. What I suggested, which will probably be the easiest, is to use encapsulation and referencing back to `BigDecimal` for the implementation.


The work around you made now is to disable the upscale/downscale functionality which is avoiding the problem but not resolving it. This is robbing us of the golden opportunity to discover any other issues that might surface especially since your use case uncovered the first. This just being a delay as you will start from scratch again, with the same frustrations, once you update. ...sorry for that but just stating the obvious.

What I would suggest, and since you are only using a specific subset of the `BigDecimal` public methods you at least don't have to to do all the exposed methods (which if you did of course that would be awesome and saves someone else having to do it later). Add for example the `setScale` method to [bsh.Primitive](https://github.com/beanshell/beanshell/blob/master/src/main/java/bsh/Primitive.java)

```java
public BigDecimal setScale(int newScale) {
   if (value instanceof BigDecimal) // this might not be required and may always be false
      return ((BigDecimal) value).setScale(newScale);
   // which may just be this one liner for each encapsulated method implementation
   return new BigDecimal(s).setScale(newScale);
}
``` 
From the top of my head and not tested but I think you get the idea. Running the code in my head produced the comments =) If you manage to make this work it would be welcome to see as a PR, please.

This will have to be done for all the `BigInteger` public methods as well for all the non float primitive numbers.

Hope this goes towards answering your question?... let us know what you find.

**Comment by nickl-** [comment] 2022-12-28 01:03
This turns out to be quite the mess again, fun, fun, fun =)

Our original assessment was incorrect, a lot of work was done on the `Primitive` class in order to include `BigInteger` and `BigDecimal` as standard data types, which can probably account for considering adding the delegate methods to `Primitive`. The problem is slightly more complicated than that...of course.

The error message didn't help either, which makes reference to `Primitive` and how the method we are calling were looked for there and not found, leading us to believe this is where the problem is. 

```
// Error: Evaluation Error: Error in method invocation: Method setScale(int, RoundingMode) not found in class'bsh.Primitive'
``` 
Of course adding the methods on `Primitive` also solves the immediate problem, since BeanShell is looking for the methods there, it will gladly accept them if found, being none the wiser. In fact the `Primitive` class should never have been exposed in the first place. Only compounded now because the added `java.math` classes have a plethora of instance methods defined which were not the case for the primitives and wrapper types, they rely more on static methods, and the exposed `Primitive` only became more prominent.

As I explained at https://github.com/beanshell/beanshell/issues/569#issuecomment-553274095, which can be closed by the way and bundled in with this issue, as they are both symptoms of the same issue. The `Primitive` class serves a very particular and special purpose, because everything in BeanShell is a `java.lang.Object` and all primitives are boxed in by their wrapper types and indistinguishable. Basically without the `Primitive` class we would have no way to attach TYPE to value.

Additionally Primitive also distinguishes between unassigned or void, as well as null assigned, in bean script from their counterparts in JAVA. Which since BeanShell is written in JAVA are used and relied upon for their purpose in JAVA and cannot also be borrowed or cause ambiguity. So `Primitive` to the bean script, represents the type, value, state, reference, or lack thereof, of value instances in script and cannot be an object instance in itself. For `int i = 1;` the variable `i` is of type primitive `int` with a value of 1 even though BeanShell is using a `Primitive` instance to represent `i` that has no meaning to the script. In the same way `new BigDecimal( 123.456789 )` is a new instance of `BigDecimal` with all its method and fields exposed, `null` is `null` and `void` is `void`, for all intents and purposes `bsh.Primitive` does not exist...or that is how it should be.

This is not an idle wish, ideal scenario, personal preference, new requirement or specification but has always been the intention, as is evident from the remarks and debug message prompting such, left in the `Name` class where `Primitive`'s erroneous exposure was facilitated.

https://github.com/beanshell/beanshell/blob/60c74f11fec554dea1068d75cbbbcbe6ecbcb5f9/src/main/java/bsh/Name.java#L827-L833

There also exists two separate paths to accessing methods on instances represented by `Primitive` for the `new` instance it starts at `BSHPrimarySuffix`

https://github.com/beanshell/beanshell/blob/60c74f11fec554dea1068d75cbbbcbe6ecbcb5f9/src/main/java/bsh/BSHPrimarySuffix.java#L183-L208

Here we can also see the origin of the notorious "Error in method invocation" error message received when the `setScale(int, RoundingMode)` method could not be found. When calling this mehod from a reference like `varDec.setScale(int, RoundingMode);` the call stack takes another path starting at `BSHMethodInvocation` which will produce exactly the same error.

https://github.com/beanshell/beanshell/blob/60c74f11fec554dea1068d75cbbbcbe6ecbcb5f9/src/main/java/bsh/BSHMethodInvocation.java#L68-L97

Because yes the code is duplicated and as suggested by the comments should "refactored for common functionality". If we instead expose the instance and not the wrapper, the methods can be found, and works as expected. Because the instance is in place of the helper class it is effectively hidden from the script completely, nothing can be accessed or invoked, because it isn't available anymore. When invocation is done, the return value gets wrapped again and what you believe to be a `BigDecimal` value is in fact a `Primitive` helper but not so that you will notice.

If that was only the least of it...so as it states we were "allowing bsh.Primitive to peek through for debugging" and debugging over the last 20 years we apparently did. Meticulously recorded as proofs in unit tests none the less, since there are countless assertions now failing as they can no longer reference `bsh.Primitive` as script variables, nor are the methods they were previously able to invoke on the instance available anymore. How I do love munging passing tests to make a new feature to work, a whole new can of spaghetti worms are still to be sorted through.

**Closed** 2023-01-03 20:14 UTC

**Comment by opeongo** [comment] 2023-01-03 22:45
The following compiles and runs successfully under Java but now throws a parse error with BeanShell:

```java
public class ParseYieldTest {
    public void yield() {
    }

    public static void main(String[] args) {
        new ParseYieldTest().yield();
    }
}
```

**Comment by opeongo** [comment] 2023-01-03 22:57
I feel a little bit uneasy about the new operators (null coalescing, elvis, compare, etc).  For some people these might be nice to have, but it seems like we are getting ahead of Java.  I know that the Java folks are slow to implement features that are available in other languages and this is frustrating.   I expect that they will get there with some day with a null coalescing operator.  At that point we may (or may not, depending) have a source code compatibility issues.

My guess is that you wont ever see an elvis or comparison operator in Java, because these just don't carry their weight.

**Comment by nickl-** [comment] 2023-01-04 00:04
> The following compiles and runs successfully under Java but now throws a parse error with BeanShell:

The yield keyword was just added to the grammar not implemented yet. Is yield not a reserved word?

**Comment by nickl-** [comment] 2023-01-04 00:20
> I feel a little bit uneasy about the new operators

You don't have to use them if you don't want to.
